### ISSUE TITLE
tap on map markers doesn't work on mobile

### ISSUE THREAD

**Issue by elf-pavlik** [ehecame/vientos-nahual#23]
it should open project's profile but on mobile devices nothing happens

**Comment by samurex** [comment]
it seems that the problem is with the Polymer DOM mode, leaflet-extras map component works well with shaddy dom mode

**Comment by elf-pavlik** [comment]
we discussed it via chat and decided to stop using old and not maintained `<leaflet-map>` component and just use leaflet directly in our custom `<vientos-map>` component
