### ISSUE TITLE
Places with no proposal and no organization in map

### ISSUE THREAD

**Issue by ralexrdz** [ehecame/vientos-nahual#58]
Pins are being shown when not having proposals or organizations

**Comment by elf-pavlik** [comment]
Yeah, we just need to have some job (maybe run with cron every 10 min) to delete all places which don't have reference from a proposal or organization.

**Comment by elf-pavlik** [comment]
Actually we can handle issue for that here https://github.com/vientos/vientos-service/issues/17
Once we fix it and close it there we can close this one here as well.
