### ISSUE TITLE
cannot natively create grid with iron-list 

### ISSUE THREAD

**Issue by furenku** [ehecame/vientos-nahual#7]
It seems iron-list's element placement structure cannot be easily modified without writing custom css/js. It uses absolute positioning and transform3d, so any attempt at re-arranging brings additional complexity.

The solution I came up is to revert to normal dom-repeats and use iron-flex-layout for the flex grid.

```html


<link rel="import" href="../bower_components/iron-flex-layout/iron-flex-layout.html">
<link rel="import" href="../bower_components/iron-flex-layout/iron-flex-layout-classes.html">

```

```html
<style is="custom-style" include="shared-styles iron-flex iron-positioning iron-flex-alignment">
   ...
</style>
```

```html

   <section id="grid" class="horizontal around-justified layout wrap">


         <template is="dom-repeat" items="[[itemsArray]]">

            <paper-card>
            <paper-card>

            ...

         </paper-card>

      </div>

   </template>

</section>
```

**slightly off-topic**
The great thing about iron-list is the way it lazily loads components into the DOM, which makes it great for one column infinite-scrolling card based layouts

**Comment by elf-pavlik** [comment]
why do you see the need to use a grid instead of simply using a list?

**Comment by elf-pavlik** [comment]
@furenku have you looked at https://www.webcomponents.org/element/PolymerElements/iron-list#user-content-grid-layout

**Comment by elf-pavlik** [comment]
seems to work now :smile:
